/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm.vue')['default']
    PlanLimitModal: typeof import('./src/components/PlanLimitModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarContents: typeof import('./src/components/SidebarContents.vue')['default']
  }
}
